services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysqldb_data:/var/lib/mysql

  app:
    build: .
    container_name: ecommerce-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/ecommerce_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: 'true'
      JWT_SECRET: 8f3c2e7a1b4d5f6c9e8b7a6d5c4f3e2b1a0d9c8b7e6f5a4c3b2d1e0f9c8b7a6d
      JWT_EXPIRATION: 86400000 # 24 horas en milisegundos

volumes:
  mysqldb_data:
